name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::torchaudio=2.1.0
  - pytorch::pytorch-cuda=11.8
  - nvidia::cuda-toolkit=11.8
  - nvidia::cuda-nvcc=11.8
  - nvidia::cuda-cccl=11.8.89
  - conda-forge::gxx_linux-64=11
  - conda-forge::gcc_linux-64=11
  - ninja
  - plyfile
  - tqdm
  - numpy<2
  - pip:
    - opencv-python<4.10.0
    - joblib